<?php
return array (
  7 => 
  array (
    'id' => '7',
    'catid' => '6',
    'typeid' => '0',
    'title' => '双创巡展日',
    'style' => '',
    'thumb' => 'http://localhost/cms/pc/uploadfile/2017/0514/thumb_500_280_20170514124238265.jpg',
    'keywords' => '双创巡展',
    'description' => '戊二醛 让我去二未确认群翁山东分公司答复 是的发个',
    'posids' => '1',
    'url' => 'http://localhost/cms/pc/index.php?m=content&c=index&a=show&catid=6&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1494730338',
    'updatetime' => '1494989731',
    'hitsid' => 'c-1-7',
    'views' => '14',
    'yesterdayviews' => '11',
    'dayviews' => '2',
    'weekviews' => '3',
    'monthviews' => '14',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '6',
    'typeid' => '0',
    'title' => '轮播图1',
    'style' => '',
    'thumb' => 'http://localhost/cms/pc/uploadfile/2017/0510/20170510081705382.jpg',
    'keywords' => '轮播图1',
    'description' => '',
    'posids' => '1',
    'url' => 'http://localhost/cms/pc/index.php?m=content&c=index&a=show&catid=6&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1494418339',
    'updatetime' => '1494991184',
    'hitsid' => 'c-1-1',
    'views' => '5',
    'yesterdayviews' => '1',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '5',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '6',
    'typeid' => '0',
    'title' => '轮播图2',
    'style' => '',
    'thumb' => 'http://localhost/cms/pc/uploadfile/2017/0510/20170510083509450.jpg',
    'keywords' => '轮播图2',
    'description' => '',
    'posids' => '1',
    'url' => 'http://localhost/cms/pc/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1494419680',
    'updatetime' => '1494991189',
    'hitsid' => 'c-1-2',
    'views' => '10',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '10',
  ),
);
?>