<?php
return array (
  8 => 
  array (
    'id' => '8',
    'catid' => '21',
    'typeid' => '0',
    'title' => '个梵蒂冈色瑞特让他',
    'style' => '',
    'thumb' => 'http://localhost/cms/pc/uploadfile/2017/0517/20170517125312329.jpg',
    'keywords' => '梵蒂冈 瑞特',
    'description' => '',
    'posids' => '0',
    'url' => 'http://localhost/cms/pc/index.php?m=content&c=index&a=show&catid=21&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1494996708',
    'updatetime' => '1495001902',
    'hitsid' => 'c-1-8',
    'views' => '7',
    'yesterdayviews' => '0',
    'dayviews' => '7',
    'weekviews' => '7',
    'monthviews' => '7',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '21',
    'typeid' => '0',
    'title' => '带我飞我二哥',
    'style' => '',
    'thumb' => 'http://localhost/cms/pc/uploadfile/2017/0517/20170517031853172.jpg',
    'keywords' => '二哥',
    'description' => '',
    'posids' => '0',
    'url' => 'http://localhost/cms/pc/index.php?m=content&c=index&a=show&catid=21&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1495005495',
    'updatetime' => '1495005539',
    'hitsid' => 'c-1-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>