<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '12',
    'typeid' => '0',
    'title' => '中国创业学院',
    'style' => '',
    'thumb' => 'http://localhost/cms/pc/uploadfile/2017/0512/20170512025620543.jpg',
    'keywords' => '中国 学院',
    'description' => '2015年3月24日，清华大学推出系列创业在线课程，将学校的创业课程资源向社会免费开放。目前，公众只要注册成为学堂在线用户并进入创业栏目   ',
    'posids' => '0',
    'url' => 'http://localhost/cms/pc/index.php?m=content&c=index&a=show&catid=12&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1494572027',
    'updatetime' => '1494919998',
    'hitsid' => 'c-1-4',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '3',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '12',
    'typeid' => '0',
    'title' => '创业加油站',
    'style' => '',
    'thumb' => 'http://localhost/cms/pc/uploadfile/2017/0514/20170514105013186.jpg',
    'keywords' => '加油站',
    'description' => '',
    'posids' => '1',
    'url' => 'http://localhost/cms/pc/index.php?m=content&c=index&a=show&catid=12&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1494730166',
    'updatetime' => '1494991174',
    'hitsid' => 'c-1-6',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '4',
  ),
);
?>